# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "iBurn.xcodeproj")
    build_app(workspace: "iBurn.xcworkspace", scheme: "iBurn")
    upload_to_testflight
    upload_symbols_to_crashlytics
  end

  lane :refresh_dsyms do
	  download_dsyms                  # Download dSYM files from iTC
	  upload_symbols_to_crashlytics   # Upload them to Crashlytics
	  clean_build_artifacts           # Delete the local dSYM files
	end
end


